services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - '15672:15672'

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    env_file:
      - services/auth-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    env_file:
      - services/user-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    env_file:
      - services/order-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    env_file:
      - services/payment-service/.env
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    env_file:
      - services/notification-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    env_file:
      - api-gateway/.env
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service

  backend-for-frontend:
    build:
      context: .
      dockerfile: backend-for-frontend/Dockerfile
    env_file:
      - backend-for-frontend/.env
    ports:
      - '3010:3010'
    depends_on:
      - api-gateway

volumes:
  postgres_data:
